@startuml

:Developer:
:用户: as user
:Admin:

(应用) as app
(模板) as template
(可见性) as visible
(流程) as workflow

note right of visible
    可见性收到 (版本控制,权限,灰度)影响
end note


user -- visible

Admin --> visible: 设置可见性

visible --> app: 选择应用
visible --> template: 选择模板
visible ---> workflow: 列出自建流程

template --> workflow: 补足参数

app --> (trigger): contains
app --> (action)

Developer ---> app: 定义

rectangle form {

    (auth)
    (dynamic data)
    (check)
    (variable:dsl)
}

(Node)

trigger --> (Node)
action --> (Node)

Node --> form
Node -> workflow: many to one

:用户: --> form
:用户: --> (authAccount)

authAccount -> authAccount:定时刷新

authAccount <-- auth

workflow --> 流程引擎

'流程引擎 -> Node: callback
newpage

package Auth {
  (是否是管理员)
}

package visible {

   (app可见性)
   (trigger/action可见性)
   (returns 可见性)
}

package App {
    (listAppService)
}

@enduml