@startuml



package Form {

    (事件总线) as eventbus
}


package Event {

    (事件定义) as eventDef

    (自定义事件定义) --|> eventDef
    (官方预定义事件) --|> eventDef

    (事件) as event
}

package Component {
    /'
    我们提供base component， 用户可基于这一套base component config 甚至更底层构建一套component
    这一套component应该是响应式的，组件内的逻辑是封闭的，以sheet为例
    '/
    (基础组件库) as (single)
    (属性) as property
    (组合多个基础组件) as collect
    (方法) as function

    note right of function
        需要设计一套支持
        用户定义收到event
        进行函数处理的config/dsl
    end note

    collect --|> (single): one to many


    (single) --> property: 对外暴露
    (single) --> function

    property --> (校验)
    property --> (默认值)

    eventbus <--> event: dispatch event

    function <--> event: send event



}



@enduml