@startuml

rectangle submit {
   (选择触发器/执行器) as node
   (选择应用) as app
   (填写表单) as form

   (授权/取消授权) as auth
   (表单校验) as formCheck
   (注册触发器)
}

 rectangle flowManagement {
    (查看流程)
    (启动流程)
    (触发流程)
    (删除流程)
    (停用流程)
 }

user --> submit
user --> flowManagement
user --> (查看模板)
user --> (拷贝工作流)
user --> (查看流程日志)

应用 --> (触发流程)

rectangle appManagement {
    (停用/启用app)
    (查看使用量)
}

rectangle templateManagement {
    (配置模板列表)
    (配置模板项)
    (配置模板组)
}

admin --> appManagement
admin --> templateManagement

rectangle customApp {
    (定义表单组件)
    (定义组件间关系)
    (定义授权)
    (定义触发器/执行器元数据)
    (定义应用元数据)
}

developer -right-> customApp

@enduml